language: node_js
node_js:
  - "8"
  - "9"
  - "10"
sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common python-software-properties
  - sudo add-apt-repository ppa:dhor/myway -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y graphicsmagick imagemagick
